---
title: "Introduction"
author: "andersc"
date: "Wednesday, August 13, 2014"
output: html_document
---

# Book - Statistics (Concepts and Controversies)

## Contents

* 数据的产生
* 数据分析
* 概率
* 统计推断

## Preface

目标：把统计学以不同角度呈现，不把统计作为专业的工具，而是作为一个人应有的文化素养。

方式：强调观念，而非方法。

心理学家言：想要加强对日常生活中数据与机遇合理推断之能力，精通数学并无太大帮助。

一言以蔽之，**Quantitative Literacy**

## What is Statistics

统计学用于处理数据。数字本身不是数据，需结合上下文才能赋予数字有效的信息。统计学从数据中找出信息，得出结论。

常见工具是图表和计算，以及常识判断。

## Cases

轶闻引入注目，深入人心，但总不足以成为判断的依据，且易产生误导。轶闻由于其鲜活性，常常比数据更有优势。

例子：

* 购物前，网上评论与同事评价；
* 某些权威、专家的言论与事实；（考虑该专家是否有真正可信服之研究结果）

**数字不会说谎，但说谎的人会想到办法**

谨慎审视数据的来源。

* 人均收入 6K？
* 平均房价 12K？
* 失业率 5%？

## 相关性与因果关系

* 设有赌场的县 -> 犯罪率高？
* 受教育多者 -> 收入更高？
* 网上修课者 -> 比常规教室修课者好？

## 变化 - Variability

（美国）政府的数据是根据好的样本得到的，是好的估计，但未必是100%的事实。很多数据，尤其是和经济有关者，本来就易变。

有的人会对微小的变动做出过度反应。很多人认为数字等同于“事实”，难以以概率的观点看待问题。事实上，数字仅是一种简化的表示法，它描述的是一个**范围**。

**运气的作用**

* 绝杀球 vs. 实力
* 股市之变化
* 后见之明
* 球员成绩的变化

## 爱因斯坦的话

数学定律不能百分百确定地用于显示生活中；能百分百确定地用数学定律描述的，就不是现实生活。

面对一个数字，考虑**置信区间（Confidence Interval）**及**统计显著的（Statistically Significant）**。

## 数据与社会价值观

要用统计数据骗人很容易，但不用统计的话会更容易。

* 失业率，如何定义，如何收集数据
* 自杀率（对自杀的理解，对抑郁症的理解）







